version: "3.8"

services:
  sboard_db_service:
    image: mysql
    container_name: sboard_db_container
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sboard
      MYSQL_USER: sboard
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    networks:
      - springboot-mysql-net

  sboard_app_service:
    build: .
    container_name: sboard_app_container
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - sboard_db_service
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge