version: "3.8"
services:
  mysql_db_service:
    image: mysql 
    container_name: mysql_db_container
    ports: 
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sjo112777
      MYSQL_USER: sjo112777
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db/mysql/data:/var/lib/mysql